name: Kintone Deploy
on:
  push:
    branches: [ main ]
env:
  KINTONE_BASE_URL: ${{secrets.KINTONE_BASE_URL}}
  KINTONE_PASSWORD: ${{secrets.KINTONE_PASSWORD}}
  KINTONE_USER: ${{secrets.KINTONE_USER}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v25
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #    node-version: '16'
      #   #  cache: 'npm'
      # - run: npm install
      # # - run: npm run deploy
      # - run: echo "🍏 This job's status is ${{ job.status }}."
